account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', views.Logout, name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
]

project/urls.py
from django.urls import path
from .import views

app_name = "project"

urlpatterns = [
    path('', views.home, name="home"),
    path('create-project/', views.createProject, name="create-project"),
    path('update-project/<int:id>/', views.updateProject, name="update-project"),
    path('accept-project/<int:id>/', views.accept_project, name="accept-project"),   
    path('close-project/<int:id>/', views.close_project, name="close-project"),   
    path('workspace/', views.workspace, name="workspace"),   
    path('resolved projects/', views.all_closed_projects, name="all-closed"),   
    path('project-detail/<int:id>/', views.project_detail, name="project-detail"),   
    path('company-details/<int:id>/', views.company_details, name="company-details"),   
    path('all-closed-projects', views.all_closed_projects, name="all-closed-projects"),   
]

project/models.py
from django.db import models
from account.models import *
from django.conf import settings
from django.urls import reverse


# Create your models here.

class Company(models.Model):
    name =  models.CharField(max_length=200)
    email =  models.CharField(max_length=400)
    contact =  models.CharField(max_length=200)
    address =  models.CharField(max_length=400)
    town_city =  models.CharField(max_length=400)
    

    class Meta:
        verbose_name_plural = 'companies'

    def get_absolute_url(self):
        return reverse('project:company-details', args=[self.id])

    def __str__(self):
        return self.name
    

class Project(models.Model):
    choices = (
        ('Active','Active'),
        ('Completed','Completed'),
        ('Pending','Pending'),
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE,null=True)
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='engineer',null=True,blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='created_by',null=True,blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    is_resolved = models.BooleanField(default=False)
    accepted_date = models.DateTimeField(null=True,blank=True)
    closed_date = models.DateTimeField(null=True,blank=True)
    project_status = models.CharField(max_length=15,choices=choices)
    
    class Meta:
        ordering = ['-date_created']

    
    def get_absolute_url(self):
        return reverse('project:project-detail', args=[self.id])
    
    def __str__(self):
        return self.title
    
class Message(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
        
    class Meta:
        ordering = ['-created', '-updated']

        def __str__(self):
            return self.body[0:50]

project/forms.py
from django import forms
from .models import *

class CreateProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        
class UpdateProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = ['assigned_to', 'created_by',]

project/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from account.models import *
from django.contrib import messages
from django.db.models import Q
import datetime

# Create your views here.

def staff_view(request):
    q = request.GET.get('q') if request.GET.get('q') != None else''
    projects = Project.objects.filter(Q(company__name__icontains=q) | Q(title__icontains=q) | Q(description__icontains=q), project_status='Pending')
    context = {'projects':projects}
    return render(request, 'home.html', context)

def customer_view(request):
    q = request.GET.get('q') if request.GET.get('q') != None else''
    projects = Project.objects.filter(Q(company__name__icontains=q) | Q(title__icontains=q) | Q(description__icontains=q),created_by=request.user)
    context = {'projects':projects}
    return render(request, 'home.html', context)    

@login_required
def home(request):
  if request.user.is_staff:
      return staff_view(request)
  else:
      return customer_view(request)

# def createproject(request):
#     if request.method == 'POST':
#         form = CreateprojectForm(request.POST)
#         if form.is_valid():
#             var = form.save(commit=False)
#             var.project_status = 'Pending'
#             var.save()
#             messages.info(request, 'Your project has been successfully submitted')
#             return redirect('account:dashboard')
#         else:
#             messages.warning(request,'Something went wrong')
#             return redirect('project:home')
#     else:
#         form = CreateprojectForm()
#         context = {'form':form}
#         return render(request, 'projects/clients/project_form.html',context)

def createProject(request):
    form = CreateProjectForm
    companies = Company.objects.all()
    if request.method == 'POST':
        company_name = request.POST.get('company')
        company_email = request.POST.get('company-email')
        company_contact = request.POST.get('company-contact')
        company_address = request.POST.get('company-address')
        company_city = request.POST.get('company-city')
        company,created = Company.objects.get_or_create(name=company_name,email= company_email,contact=company_contact,
                                                        address= company_address,town_city=company_city)
        
        Project.objects.create(
            company=company,
            created_by = request.user,
            title = request.POST.get('title'),
            description = request.POST.get('description'),
            project_status = 'Pending'
        )
        return redirect('project:home')


    context={'form':form,'companies':companies}
    return render(request, 'projects/clients/project_form.html', context)
    
#project detaisl
def project_detail(request,id):
    project = project.objects.get(id=id)
    project_messages = project.message_set.all()
    if request.method == 'POST':
        message = Message.objects.create(
            user=request.user,
            project=project,
            body=request.POST.get('body')
        )   
       # room.participants.add(request.user.name)
        return redirect('project:project-detail', id=project.id)
    t = UserBase.objects.get(user_name = project.created_by )
    projects_per_user = t.created_by.all()
    context = {'project':project, 'projects_per_user':projects_per_user,'project_messages':project_messages}
    return render(request, 'projects/clients/project_detail.html', context)

def updateProject(request,id):
    project = project.objects.get(id=id)
    form = UpdateProjectForm(instance=project)
    
    if request.method =='POST':
        project.title = request.POST.get('title')
        project.description = request.POST.get('description')
        project.save()
        return redirect('project:home')

    context = {'form':form, 'project':project}
    return render(request, 'projects/clients/update_project_form.html', context)

def company_details(request,id):
    project = project.objects.get(id=id)
    user = UserBase.objects.get(id=id)
    context = {'user':user,'project':project}
    return render(request, 'projects/clients/company-details.html',context)

""" For Engineers """

#view project queue
# def project_queue(request):
#     projects = project.objects.filter(project_status='Pending')
#     context = {'projects':projects}
#     return render(request, 'projects/staff/project_queue.html', context)

#accept a project from the queue
def accept_project(request,id):
    project = project.objects.get(id=id)
    project.assigned_to = request.user
    project.project_status = 'Active'
    project.accepted_date = datetime.datetime.now()
    project.save()
    messages.info(request, 'project has been accepted.Please resolve as soon as possible')
    return redirect('project:workspace')

#close a project
def close_project(request,id):
    project = project.objects.get(id=id)
    project.project_status = 'Completed'
    project.is_resolved = True
    project.closed_date = datetime.datetime.now()
    project.save()
    messages.info(request, 'project has been closed.')
    return redirect('project:home')
    
#projects engineer is working on
def workspace(request):
    projects = Project.objects.filter(assigned_to=request.user,is_resolved=False)
    company = Company.objects.all()
    context = {'projects':projects}
    return render(request, 'projects/staff/workspace.html', context)

#all closed/resolved projects
def all_closed_projects(request):
    projects = Project.objects.filter(assigned_to=request.user,is_resolved=True)
    projects.closed_date = datetime.datetime.now()
    context = {'projects':projects}
    return render(request, 'projects/staff/all_closed_projects.html', context)
            

templates/projects/clients/company-details.html
{% extends "../../base.html" %}

{% block content %}

<section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">{{project.company.name }}</h2>
          <h1 class="text-white text-3xl title-font font-medium mb-4">{{project.title}}</h1>
          <div class="flex mb-4">
            <a href="{{project.get_absolute_url}}" class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Overview</a>
            <a href="{{project.company.get_absolute_url}}" class="flex-grow text-indigo-400 border-b-2 border-indigo-500 py-2 text-lg px-1">Company</a>
            {% if not request.user.is_staff %}
            <a href="{% url 'project:update-project' project.id %}" class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Update</a>
            {% endif %}
          </div>

          <div class="flex border-t border-gray-800 py-2">
            <span class="text-gray-500">Email</span>
            <span class="ml-auto text-white">{{project.company.email}}</span>
          </div>
          <div class="flex border-t border-gray-800 py-2">
            <span class="text-gray-500">Contact Details</span>
            <span class="ml-auto text-white">{{project.company.contact}}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-800 py-2">
            <span class="text-gray-500">Company Address</span>
            <span class="ml-auto text-white">{{project.company.address}}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-800 py-2">
            <span class="text-gray-500">City/Town</span>
            <span class="ml-auto text-white">{{project.company.town_city}}</span>
          </div>
        </div>
      </div>
    </div>
  </section>




{% endblock %}

templates/projects/clients/project_detail.html
{% extends "../../base.html" %}
{% load static %}

{% block content %}

<section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">{{project.company.name}}</h2>
        <h1 class="text-white text-3xl title-font font-medium mb-4">{{project.title}}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-400 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
          <a href="{{project.company.get_absolute_url}}" class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Company</a>
          {% if not request.user.is_staff %}
          <a href="{% url 'project:update-project' project.id %}"  class="flex-grow border-b-2 border-gray-800 py-2 text-lg px-1">Update</a>
          {% endif %}
        </div>
        <p class="leading-relaxed mb-4">{{project.description}}</p>
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Accepted Date</span>
          <span class="ml-auto text-white">{{project.accepted_date}}</span>
        </div>
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Created By</span>
          <span class="ml-auto text-white">{{project.created_by}}</span>
        </div>
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Project Status</span>
          <span class="ml-auto text-white">{{project.project_status}}</span>
        </div>
        <div class="flex border-t border-gray-800 py-2">
          <span class="text-gray-500">Assigned Engineer</span>
          {% if project.assigned_to %}
          <span class="ml-auto text-white">{{project.assigned_to}}</span>
          {% else %}
          <span class="ml-auto text-white">Not Yet Assigned</span>
          {% endif %}
        </div>
        <div class="flex border-t border-b mb-6 border-gray-800 py-2">
          <span class="text-gray-500">Resolved?</span>
          {% if project.is_resolved %}
          <span class=" badge bg-success ml-auto text-white ">Yes</span>
          {% else %}
          <span class=" badge bg-danger ml-auto text-white ">Not Yet</span>
          {% endif %}
        </div>
       
        <div class="flex">
          {% if request.user.is_staff and not project.is_resolved %}
          <a href="{% url 'project:close-project' project.pk %}" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Confirm Resolution</a>
          <a href="{% url 'project:accept-project' project.pk %}" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Accept Project</a>
      {% endif %}  
        </div>
      </div>
      <div class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded">
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-white">Chat Room</h1>
          <div>
              {% for message in project_messages %}
              <div>
                <small style="font-size:18px;color:red;">@{{message.user}}  <small style="padding-left:130px;font-size:15px;color:white">{{message.created|timesince}} ago</small></small>
                <br>
                <br>
                <p style="font-family:monospace">{{message.body}}</p>
                <hr>
              </div>
              {% endfor %}
          </div>
          <br>
          <br>
          <div>
            <form method="POST" action="">
              {% csrf_token %}
              <input class="w-full bg-gray-800 rounded border border-gray-700 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" type="text" name="body" placeholder="Enter message here" />
            </form>
          </div>
    </div>
    </div>
  </div>
</section>



{% comment %} <div class="container">
    <div class="row">
      <div class="col">
        <div class="card text-white bg-dark mb-3">
            <h4 class="header">All Projects By this Company</h4>
                {% for project in projects_per_user %}
                <span class="sp">{{project.title}}<a href="{{project.get_absolute_url}}"><span class="sp1">View Project</span></a>
                {% endfor %}
        </div>
    </div>
    <div class="col-6">
        <div class="card text-white bg-dark mb-3">
        <span class = "sp">Project Title: <span class="sp1">{{project.title}}</span></span>
        <br>
            <span class="sp">Description: <span class="sp1">{{project.description}}</span></span>
            <br>
            <span class = "sp">Date Created:  <span class="sp1">{{project.date_created|timesince }} ago</span></span>
            <br>
            <span class = "sp">Accepted Date: <span class="sp1">{{project.accepted_date|timesince }} ago</span></span>
            <br>
            {% if project.is_resolved %}
            <span class="sp">Resolved? : <span class="badge bg-success">Yes</span></span>
            {% else %}
             <span class="sp">Resolved? : <span class="badge bg-danger">Not Yet</span></span>
            {% endif %}
            <br>
            <span class = "sp">Assigned to:  <span class="sp1">{{project.assigned_to}}</span></span>
            <br>
            <span class = "sp">Created By: <span class="sp1">{{project.created_by}}</span></span>
            <br>
            <span class = "sp">Project Status:   <span class="sp1-active">{{project.project_status}}</span></span>
            <br>
      </div>
    </div>
    <div class="b" style="padding-left:280px;">
    {% if request.user.is_staff and not project.is_resolved %}
    <a href="{% url 'project:close-project' project.pk %}" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal" style="width:400px;" data-bs-toggle="modal" data-bs-targets="examspanleModal">Confirm Resolution</a>
    {% endif %}

    {% if request.user.is_authenticated and not project.is_resolved %}
    <a href="{% url 'project:update-project' project.pk %}" class="btn btn-spanrimary">Update project</a>
    {% endif %}

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to close the project?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <a href = "{% url 'project:close-project' project.pk %}" class="btn-btn-primary">Save </a>
        </div>
      </div>
    </div>
  </div>
    </div>
    </div>
</div>  {% endcomment %}

{% comment %} <style>
    .row{
        spanadding-left:60spanx;
        spanadding-tospan:60spanx;
    }
    .you{
        background-color:black;
    }

    .you1{
        background-color:white;
    }

    .t1{
        color:red;
        font-size:15spanx;
    }
</style>

<header class="header">
    
</header> {% endcomment %}

{% comment %} <div class="row">
    <div class="col-md-6 ">
      <div class="card mx-auto you" style="width:30rem;">
        {% comment %} <img class="img-fluid" alt="Resspanonsive image" src="{{ spanroduct.image.url }}"> {% endcomment %}
        {% comment %} <div class="card-body">
          <h5 class="card-title mb-3">  class="t1">project Title: <> <small>{{project.title}}</small></h5>
          <span>  class="t1">project Number:<> <small> {{project.project_number}}</small></span>
          <span class="card-text"> class="t1">Descrispantion<>{{project.descrispantion}}</span>

        <div class="row">
            <div class="col">
                 class="t1">Date Created : <>{{project.date_created|timesince}} ago
            </div>
        </div>

        <div class="row">
            <div class="col">
                {% if project.is_resolved %}
                 class="t1">Resolved? : <>  class="badge bg-success">Yes<>
                {% else %}
                 class="t1">Resolved? : <>  class="badge bg-danger">Not Yet<>
                {% endif %}
            </div>
            <div class="col">
                 class="t1">Accespanted Date : <> <small> {{project.accespanted_date|timesince}}</small>
            </div>
        </div>

        <div class="row">
            <div class="col">
                 class="t1">Created By : <> <small> {{project.created_by}}</small>
            </div>
            <div class="col">
                 class="t1">project Status : <> <small> {{project.project_status}}</small>
            </div>
        </div>
      </div>
    </div>

    <div class="col-md-6">
        <div class="card mx-auto you1" style="width:30rem;">
            <div class="card-body">
                <h5 class="card-title mb-3">All projects created by {{projects.created_by}}</h5>
                {% for project in projects_spaner_user %}
                <span class="card-text">{{project.project_number}}</span> <a href="{% url 'project:project-detail' project.spank %}">View project</a>
                {% endfor %}

            </div>
        <div>
    </div> {% endcomment %}
{% comment %} </div> {% endcomment %}

{% comment %} {% if request.user.is_staff and not project.is_resolved %}
<a href="{% url 'project:close-project' project.spank %}" class="btn btn-danger" data-bs-toggle="modal" data-bs-targets="examspanleModal">Confirm Resolution</a>
{% endif %}

{% if request.user.is_authenticated and not project.is_resolved %}
<a href="{% url 'project:uspandate-project' project.spank  %}" class="btn btn-spanrimary">Uspandate project</a>
{% endif %}
<div class = "modal fade" id="examspanleModal" tabindex="1" aria-labelledby="examspanleModalLabel" aria-hidden="True">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="examspanleModalLabel">Modal Title</h5>
                <button tyspane="button" class="btn-close" data-bs-dismiss="modal" aria-label="close"></button>
            </div>
            <div class="modal-body">
                Do you want to close the project
            </div>
            <div class="modal-footer">
                <button tyspane="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="close">close</button>
                <a href="{% url 'project:close-project' project.spank %}" class="btn btn-spanrimary">Save Changes</a>
            </div>
        </div>
    </div>
</div> {% endcomment %}

{% endblock %} 

templates/projects/clients/project_form.html
{% extends '../../base.html' %}

{% block content %}

<form class="form" action="" method="POST">
    {% csrf_token %}
    <section class="text-gray-400 bg-gray-900 body-font relative">
      <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-12">
          <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-white">Create Project</h1>
        </div>
        <div class="lg:w-1/2 md:w-2/3 mx-auto">
          <div class="flex flex-wrap -m-2">
            <div class="p-2 w-1/2">
              <div class="relative">
                <label for="name" class="leading-7 text-sm text-gray-400">Company Name</label>
                <input type="required" value="{{ticket.company.name}}" name="company" list="topic-list" class="w-full bg-gray-800 bg-opacity-40 rounded border border-gray-700 focus:border-indigo-500 focus:bg-gray-900 focus:ring-2 focus:ring-indigo-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                <datalist id="topic-list">
                  <select id="room_topic">
                  {% for company in companies %}
                  <option value="{{company.name}}">{{company.name}}</option>
                  {% endfor %}
                  </select>
                  </datalist>
              </div>
            </div>

            <div class="p-2 w-1/2">
              <div class="relative">
                <label for="name" class="leading-7 text-sm text-gray-400">Company Email</label>
                <input type="required" value="{{ticket.company.email}}" name="company-email" list="topic-list" class="w-full bg-gray-800 bg-opacity-40 rounded border border-gray-700 focus:border-indigo-500 focus:bg-gray-900 focus:ring-2 focus:ring-indigo-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                <datalist id="topic-list">
                  <select id="room_topic">
                  {% for company in companies %}
                  <option value="{{company.email}}">{{company.email}}</option>
                  {% endfor %}
                  </select>
                  </datalist>
              </div>
            </div>

            <div class="p-2 w-1/2">
              <div class="relative">
                <label for="name" class="leading-7 text-sm text-gray-400">Company Contact</label>
                <input type="required" value="{{ticket.company.contact}}" name="company-contact" list="topic-list" class="w-full bg-gray-800 bg-opacity-40 rounded border border-gray-700 focus:border-indigo-500 focus:bg-gray-900 focus:ring-2 focus:ring-indigo-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                <datalist id="topic-list">
                  <select id="room_topic">
                  {% for company in companies %}
                  <option value="{{company.contact}}">{{company.contact}}</option>
                  {% endfor %}
                  </select>
                  </datalist>
              </div>
            </div>

            <div class="p-2 w-1/2">
              <div class="relative">
                <label for="name" class="leading-7 text-sm text-gray-400">Company Address</label>
                <input type="required" value="{{ticket.company.address}}" name="company-address" list="topic-list" class="w-full bg-gray-800 bg-opacity-40 rounded border border-gray-700 focus:border-indigo-500 focus:bg-gray-900 focus:ring-2 focus:ring-indigo-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                <datalist id="topic-list">
                  <select id="room_topic">
                  {% for company in companies %}
                  <option value="{{company.address}}">{{company.address}}</option>
                  {% endfor %}
                  </select>
                  </datalist>
              </div>
            </div>

            <div class="p-2 w-1/2">
              <div class="relative">
                <label for="name" class="leading-7 text-sm text-gray-400">Company City/Town</label>
                <input type="required" value="{{ticket.company.town_city}}" name="company-city" list="topic-list" class="w-full bg-gray-800 bg-opacity-40 rounded border border-gray-700 focus:border-indigo-500 focus:bg-gray-900 focus:ring-2 focus:ring-indigo-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                <datalist id="topic-list">
                  <select id="room_topic">
                  {% for company in companies %}
                  <option value="{{company.town_city}}">{{company.town_city}}</option>
                  {% endfor %}
                  </select>
                  </datalist>
              </div>
            </div>

            <div class="p-2 w-1/2">
              <div class="relative">
                <label for="email" class="leading-7 text-sm text-gray-400">Project Title</label>
                <input type="text"  name="title" value="{{ticket.title}}" class="w-full bg-gray-800 bg-opacity-40 rounded border border-gray-700 focus:border-indigo-500 focus:bg-gray-900 focus:ring-2 focus:ring-indigo-900 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
              </div>
            </div>
            <div class="p-2 w-full">
              <div class="relative">
                <label for="message" class="leading-7 text-sm text-gray-400">Description</label>
                <textarea  name="description" value="{{ticket.description}}" class="w-full bg-gray-800 bg-opacity-40 rounded border border-gray-700 focus:border-indigo-500 focus:bg-gray-900 focus:ring-2 focus:ring-indigo-900 h-32 text-base outline-none text-gray-100 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"></textarea>
              </div>
            </div>
            <div class="p-2 w-full">
              <button type="submit" class="w-full flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Create Project</button>
            </div>
          </div>
        </div>
      </div>
    </section>
</form>


{% endblock %}