account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', views.Logout, name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
]

project/urls.py
from django.urls import path
from .import views

app_name = "project"

urlpatterns = [
    path('', views.home, name="home"),
    path('create-project/', views.createProject, name="create-project"),
    path('update-project/<int:id>/', views.updateProject, name="update-project"),
    path('accept-project/<int:id>/', views.accept_project, name="accept-project"),   
    path('close-project/<int:id>/', views.close_project, name="close-project"),   
    path('workspace/', views.workspace, name="workspace"),   
    path('resolved projects/', views.all_closed_projects, name="all-closed"),   
    path('project-detail/<int:id>/', views.project_detail, name="project-detail"),   
    path('company-details/<int:id>/', views.company_details, name="company-details"),   
    path('all-closed-projects', views.all_closed_projects, name="all-closed-projects"),   
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Vetlam Solutions Project Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href='https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css' rel='stylesheet'>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
  </head>
  <body class="text-gray-400 bg-gray-900 body-font"> 
        
            {% include 'navbar.html' %}
    
            {% block content %}

            {% endblock  %}

            {% include 'footer.html' %}

   
  </body>
</html>

templates/footer.html
<footer class="text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
      <a class="flex title-font font-medium items-center md:justify-start justify-center text-white">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">Vetlam Solutions </span>
      </a>
      <p class="text-sm text-gray-400 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-800 sm:py-2 sm:mt-0 mt-4">© 2024 Vetlam Solutions —
        <a href="https://twitter.com/knyttneve" class="text-gray-500 ml-1" target="_blank" rel="noopener noreferrer">This web application was developed by Tinashe Gomo</a>
      </p>
      <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
        <a class="text-gray-400">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-400">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-400">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-400">
          <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
            <circle cx="4" cy="4" r="2" stroke="none"></circle>
          </svg>
        </a>
      </span>
    </div>
  </footer>

templates/home.html
{% extends "./base.html" %}

{% block content %}

<section class="text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-white">Vetlam Solutions</h1>
          <div class="form-outline" style="padding-left:380px;padding-top:30px" data-mdb-input-init>
            <form class="header__search" method="GET" action="{% url 'project:home' %}">
              {% csrf_token %}
            <input type="text"  style="width:490px;" name="q" class="form-control" placeholder="Search Here..." aria-label="Search" />
            </form>
          </div>
      </div>
      <div class="lg:w-3/3 w-full mx-auto overflow-auto">
        {% if not request.user.is_staff %}
            <a href="{% url 'project:create-project' %}" class="text-indigo-400 inline-flex items-center md:mb-2 lg:mb-0">Create Project
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
        {% endif %}
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm bg-gray-800 rounded-tl rounded-bl">Project Title</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm bg-gray-800 rounded-tl rounded-bl">Company</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm bg-gray-800">Date Created</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm bg-gray-800">Status</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-white text-sm bg-gray-800">Assigned Engineer</th>
              <th class="w-10 title-font tracking-wider font-medium text-white text-sm bg-gray-800 rounded-tr rounded-br"></th>
            </tr>
          </thead>
          <tbody>
            {% for project in projects %}
            <tr>
              <td class="px-4 py-3">{{project.title}}</td>
              <td class="px-4 py-3"><a href="{% url 'project:home' %}?q={{project.company.name}}">{{project.company.name}}</a></td>
              <td class="px-4 py-3">{{project.date_created}}</td>
              {% if project.project_status == 'Active' %}
              <td class="px-4 py-3"><span class="badge bg-success">Active</span></td>
              {% elif project.project_status == 'Pending' %}
              <td class="px-4 py-3 text-lg text-white"><span class="badge bg-warning">Pending</span></td>
              {% elif project.project_status == 'Completed' %}
              <td class="px-4 py-3 text-lg text-white"><span class="badge bg-danger">Completed</span></td>
              {% endif %}
              <td class="px-4 py-3">{{project.assigned_to}}</td>
              <td class="w-10 text-center"><a href="{{project.get_absolute_url}}">View</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      
    </div>
</section>


{% endblock %}

templates/navbar.html
{% load static %}

{% if request.user.is_authenticated %}
<header class="text-gray-400 bg-gray-900 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a href="{% url 'project:home' %}" class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Hi {{request.user}}</span>
    </a>
    <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
      {% if request.user.is_staff %}
      <a href="{% url 'project:all-closed-projects' %}" class="mr-5 hover:text-white">All Completed Projects</a>
      <a href="{% url 'project:workspace' %}" class="mr-5 hover:text-white">Workspace</a>
      {% else %}
      <a href="{% url 'account:edit_details' %}" class="mr-5 hover:text-white">Edit Profile</a>
      {% endif %}
    </nav>
    <a href="{% url 'account:logout' %}" class="inline-flex items-center bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-gray-700 rounded text-base mt-4 md:mt-0">LOGOUT
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
  </div>
</header>
{% endif %}